"""create_tehnoloski_postupak_table

Revision ID: 0cc8c0fd5434
Revises: a1b2c3d4e5f6
Create Date: 2026-06-16 12:09:04.379196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cc8c0fd5434'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tehnoloski_postupak',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('naziv', sa.String(length=255), nullable=False),
    sa.Column('materijal_id', sa.Integer(), nullable=True),
    sa.Column('napomena', sa.Text(), nullable=True),
    sa.Column('gramatura', sa.Integer(), nullable=False),
    sa.Column('tip_papira', sa.String(length=20), nullable=False),
    sa.Column('arka_x', sa.Float(), nullable=False),
    sa.Column('arka_y', sa.Float(), nullable=False),
    sa.Column('et_xn', sa.Float(), nullable=False),
    sa.Column('et_yn', sa.Float(), nullable=False),
    sa.Column('et_xb', sa.Float(), nullable=False),
    sa.Column('et_yb', sa.Float(), nullable=False),
    sa.Column('grajfer', sa.Float(), nullable=False),
    sa.Column('naklada_dorada', sa.Integer(), nullable=False),
    sa.Column('odabir_rez', sa.String(length=5), nullable=False),
    sa.Column('brutto_araka', sa.Integer(), nullable=False),
    sa.Column('et_u_kutiji', sa.Integer(), nullable=False),
    sa.Column('kutija_na_paleti', sa.Integer(), nullable=False),
    sa.Column('kutija_tip', sa.String(length=50), nullable=False),
    sa.Column('paleta_tip', sa.String(length=50), nullable=False),
    sa.Column('naklada_tisak', sa.Integer(), nullable=False),
    sa.Column('broj_boja', sa.Integer(), nullable=False),
    sa.Column('lakirano', sa.String(length=5), nullable=False),
    sa.Column('prolazi', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tehnoloski_postupak_naziv'), 'tehnoloski_postupak', ['naziv'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tehnoloski_postupak_naziv'), table_name='tehnoloski_postupak')
    op.drop_table('tehnoloski_postupak')
    # ### end Alembic commands ###
