"""plan_stavka

Revision ID: 16cc9cb27461
Revises: da93a22079c1
Create Date: 2026-06-29 10:43:27.969794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16cc9cb27461'
down_revision: Union[str, Sequence[str], None] = 'da93a22079c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_stavka',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stroj_sifra', sa.String(length=30), nullable=False),
    sa.Column('redoslijed', sa.Integer(), nullable=False),
    sa.Column('rn', sa.String(length=40), nullable=True),
    sa.Column('naziv', sa.String(length=255), nullable=True),
    sa.Column('papir_naziv', sa.String(length=255), nullable=True),
    sa.Column('format_cm', sa.String(length=40), nullable=True),
    sa.Column('naklada', sa.Integer(), nullable=True),
    sa.Column('kontakata', sa.Integer(), nullable=True),
    sa.Column('broj_boja', sa.Integer(), nullable=True),
    sa.Column('normativ', sa.Integer(), nullable=True),
    sa.Column('otpad', sa.Integer(), nullable=False),
    sa.Column('otisaka', sa.Integer(), nullable=True),
    sa.Column('priprema_min', sa.Integer(), nullable=False),
    sa.Column('rad_min', sa.Integer(), nullable=True),
    sa.Column('pranje_min', sa.Integer(), nullable=False),
    sa.Column('sati_min', sa.Integer(), nullable=True),
    sa.Column('rok', sa.String(length=40), nullable=True),
    sa.Column('pocetak', sa.DateTime(), nullable=True),
    sa.Column('zavrsetak', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('napomena', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_stavka_redoslijed'), 'plan_stavka', ['redoslijed'], unique=False)
    op.create_index(op.f('ix_plan_stavka_stroj_sifra'), 'plan_stavka', ['stroj_sifra'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plan_stavka_stroj_sifra'), table_name='plan_stavka')
    op.drop_index(op.f('ix_plan_stavka_redoslijed'), table_name='plan_stavka')
    op.drop_table('plan_stavka')
    # ### end Alembic commands ###
