"""kontakt_extend_adresar

Revision ID: 177e4f5997ff
Revises: 453a31aad828
Create Date: 2026-06-19 10:48:52.313318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '177e4f5997ff'
down_revision: Union[str, Sequence[str], None] = '453a31aad828'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adresar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kontakt_id', sa.Integer(), nullable=True),
    sa.Column('partner_naziv', sa.String(length=255), nullable=True),
    sa.Column('naziv_pj', sa.String(length=255), nullable=True),
    sa.Column('drzava', sa.String(length=80), nullable=True),
    sa.Column('zupanija', sa.String(length=120), nullable=True),
    sa.Column('opcina', sa.String(length=120), nullable=True),
    sa.Column('grad', sa.String(length=120), nullable=True),
    sa.Column('adresa', sa.Text(), nullable=True),
    sa.Column('kilometri', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['kontakt_id'], ['kontakt.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adresar_kontakt_id'), 'adresar', ['kontakt_id'], unique=False)
    op.create_index(op.f('ix_adresar_partner_naziv'), 'adresar', ['partner_naziv'], unique=False)
    op.add_column('kontakt', sa.Column('naziv_dodatni', sa.String(length=255), nullable=True))
    op.add_column('kontakt', sa.Column('grupa', sa.String(length=100), nullable=True))
    op.add_column('kontakt', sa.Column('hbor_osiguranje', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('kontakt', sa.Column('hbor_rok_placanja_dan', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kontakt', 'hbor_rok_placanja_dan')
    op.drop_column('kontakt', 'hbor_osiguranje')
    op.drop_column('kontakt', 'grupa')
    op.drop_column('kontakt', 'naziv_dodatni')
    op.drop_index(op.f('ix_adresar_partner_naziv'), table_name='adresar')
    op.drop_index(op.f('ix_adresar_kontakt_id'), table_name='adresar')
    op.drop_table('adresar')
    # ### end Alembic commands ###
