"""normativ_4_tables_replace_tp

Revision ID: 19d8f7f70395
Revises: 0cc8c0fd5434
Create Date: 2026-06-16 12:28:38.171117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19d8f7f70395'
down_revision: Union[str, Sequence[str], None] = '0cc8c0fd5434'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('normativ',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('naziv', sa.String(length=255), nullable=False),
    sa.Column('sifra', sa.String(length=60), nullable=True),
    sa.Column('kupac', sa.String(length=150), nullable=True),
    sa.Column('serija', sa.Integer(), nullable=True),
    sa.Column('koeficijent', sa.Integer(), nullable=True),
    sa.Column('arka_x', sa.Float(), nullable=True),
    sa.Column('arka_y', sa.Float(), nullable=True),
    sa.Column('podloga', sa.String(length=255), nullable=True),
    sa.Column('gramatura', sa.Integer(), nullable=True),
    sa.Column('stupaca', sa.Integer(), nullable=True),
    sa.Column('redova', sa.Integer(), nullable=True),
    sa.Column('et_po_arku', sa.Integer(), nullable=True),
    sa.Column('et_xn', sa.Float(), nullable=True),
    sa.Column('et_yn', sa.Float(), nullable=True),
    sa.Column('et_xb', sa.Float(), nullable=True),
    sa.Column('et_yb', sa.Float(), nullable=True),
    sa.Column('napust', sa.Integer(), nullable=True),
    sa.Column('ukupno_araka', sa.Integer(), nullable=True),
    sa.Column('broj_boja', sa.Integer(), nullable=True),
    sa.Column('napomena', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_normativ_naziv'), 'normativ', ['naziv'], unique=False)
    op.create_table('normativ_boja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('normativ_id', sa.Integer(), nullable=False),
    sa.Column('redoslijed', sa.Integer(), nullable=False),
    sa.Column('naziv_boje', sa.String(length=100), nullable=False),
    sa.Column('pantone_naziv', sa.String(length=100), nullable=True),
    sa.Column('kolicina_kg_1000', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['normativ_id'], ['normativ.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_normativ_boja_normativ_id'), 'normativ_boja', ['normativ_id'], unique=False)
    op.create_table('normativ_materijal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('normativ_id', sa.Integer(), nullable=False),
    sa.Column('redoslijed', sa.Integer(), nullable=False),
    sa.Column('materijal_id', sa.Integer(), nullable=True),
    sa.Column('naziv', sa.String(length=255), nullable=False),
    sa.Column('sifra', sa.String(length=60), nullable=True),
    sa.Column('kolicina', sa.Float(), nullable=True),
    sa.Column('jedinica', sa.String(length=20), nullable=True),
    sa.Column('cijena_eur', sa.Float(), nullable=True),
    sa.Column('ukupno_eur', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['normativ_id'], ['normativ.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_normativ_materijal_normativ_id'), 'normativ_materijal', ['normativ_id'], unique=False)
    op.create_table('normativ_operacija',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('normativ_id', sa.Integer(), nullable=False),
    sa.Column('redoslijed', sa.Integer(), nullable=False),
    sa.Column('naziv_operacije', sa.String(length=200), nullable=False),
    sa.Column('stroj_naziv', sa.String(length=150), nullable=True),
    sa.Column('stroj_alias', sa.String(length=30), nullable=True),
    sa.Column('kolicina', sa.Integer(), nullable=True),
    sa.Column('norma_min', sa.Integer(), nullable=True),
    sa.Column('eur_h', sa.Float(), nullable=True),
    sa.Column('ukupno_eur', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['normativ_id'], ['normativ.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_normativ_operacija_normativ_id'), 'normativ_operacija', ['normativ_id'], unique=False)
    op.drop_index(op.f('ix_tehnoloski_postupak_naziv'), table_name='tehnoloski_postupak')
    op.drop_table('tehnoloski_postupak')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tehnoloski_postupak',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('naziv', sa.VARCHAR(length=255), nullable=False),
    sa.Column('materijal_id', sa.INTEGER(), nullable=True),
    sa.Column('napomena', sa.TEXT(), nullable=True),
    sa.Column('gramatura', sa.INTEGER(), nullable=False),
    sa.Column('tip_papira', sa.VARCHAR(length=20), nullable=False),
    sa.Column('arka_x', sa.FLOAT(), nullable=False),
    sa.Column('arka_y', sa.FLOAT(), nullable=False),
    sa.Column('et_xn', sa.FLOAT(), nullable=False),
    sa.Column('et_yn', sa.FLOAT(), nullable=False),
    sa.Column('et_xb', sa.FLOAT(), nullable=False),
    sa.Column('et_yb', sa.FLOAT(), nullable=False),
    sa.Column('grajfer', sa.FLOAT(), nullable=False),
    sa.Column('naklada_dorada', sa.INTEGER(), nullable=False),
    sa.Column('odabir_rez', sa.VARCHAR(length=5), nullable=False),
    sa.Column('brutto_araka', sa.INTEGER(), nullable=False),
    sa.Column('et_u_kutiji', sa.INTEGER(), nullable=False),
    sa.Column('kutija_na_paleti', sa.INTEGER(), nullable=False),
    sa.Column('kutija_tip', sa.VARCHAR(length=50), nullable=False),
    sa.Column('paleta_tip', sa.VARCHAR(length=50), nullable=False),
    sa.Column('naklada_tisak', sa.INTEGER(), nullable=False),
    sa.Column('broj_boja', sa.INTEGER(), nullable=False),
    sa.Column('lakirano', sa.VARCHAR(length=5), nullable=False),
    sa.Column('prolazi', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_by', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tehnoloski_postupak_naziv'), 'tehnoloski_postupak', ['naziv'], unique=False)
    op.drop_index(op.f('ix_normativ_operacija_normativ_id'), table_name='normativ_operacija')
    op.drop_table('normativ_operacija')
    op.drop_index(op.f('ix_normativ_materijal_normativ_id'), table_name='normativ_materijal')
    op.drop_table('normativ_materijal')
    op.drop_index(op.f('ix_normativ_boja_normativ_id'), table_name='normativ_boja')
    op.drop_table('normativ_boja')
    op.drop_index(op.f('ix_normativ_naziv'), table_name='normativ')
    op.drop_table('normativ')
    # ### end Alembic commands ###
