"""add_kontakt_table

Revision ID: 400927c79078
Revises: 19d8f7f70395
Create Date: 2026-06-16 12:53:14.711480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '400927c79078'
down_revision: Union[str, Sequence[str], None] = '19d8f7f70395'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kontakt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sifra', sa.String(length=30), nullable=False),
    sa.Column('naziv', sa.String(length=255), nullable=False),
    sa.Column('interni_naziv', sa.String(length=255), nullable=True),
    sa.Column('tip', sa.String(length=20), nullable=False),
    sa.Column('oib', sa.String(length=20), nullable=True),
    sa.Column('maticni_broj', sa.String(length=20), nullable=True),
    sa.Column('adresa', sa.String(length=255), nullable=True),
    sa.Column('postanski_broj', sa.String(length=10), nullable=True),
    sa.Column('mjesto', sa.String(length=100), nullable=True),
    sa.Column('drzava', sa.String(length=60), nullable=True),
    sa.Column('telefon', sa.String(length=50), nullable=True),
    sa.Column('mobitel', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('web', sa.String(length=150), nullable=True),
    sa.Column('referent', sa.String(length=150), nullable=True),
    sa.Column('valuta_placanja_dan', sa.Integer(), nullable=True),
    sa.Column('radno_vrijeme', sa.String(length=100), nullable=True),
    sa.Column('napomena', sa.Text(), nullable=True),
    sa.Column('aktivan', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kontakt_naziv'), 'kontakt', ['naziv'], unique=False)
    op.create_index(op.f('ix_kontakt_sifra'), 'kontakt', ['sifra'], unique=True)
    op.create_index(op.f('ix_kontakt_tip'), 'kontakt', ['tip'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kontakt_tip'), table_name='kontakt')
    op.drop_index(op.f('ix_kontakt_sifra'), table_name='kontakt')
    op.drop_index(op.f('ix_kontakt_naziv'), table_name='kontakt')
    op.drop_table('kontakt')
    # ### end Alembic commands ###
