"""add_reklamacija_capa

Revision ID: 453a31aad828
Revises: 400927c79078
Create Date: 2026-06-19 10:39:20.628492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '453a31aad828'
down_revision: Union[str, Sequence[str], None] = '400927c79078'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reklamacija',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('broj_predmeta', sa.String(length=20), nullable=False),
    sa.Column('vrsta', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('prioritet', sa.String(length=10), nullable=False),
    sa.Column('kategorija', sa.String(length=10), nullable=True),
    sa.Column('naslov', sa.String(length=200), nullable=False),
    sa.Column('opis', sa.Text(), nullable=False),
    sa.Column('prijavitelj', sa.String(length=100), nullable=False),
    sa.Column('kupac_dobavljac', sa.String(length=150), nullable=True),
    sa.Column('referentni_broj', sa.String(length=100), nullable=True),
    sa.Column('naziv_proizvoda', sa.String(length=200), nullable=True),
    sa.Column('broj_radnog_naloga', sa.String(length=100), nullable=True),
    sa.Column('stroj', sa.String(length=100), nullable=True),
    sa.Column('osoblje', sa.String(length=200), nullable=True),
    sa.Column('datum_prijave', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('datum_azuriranja', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('datum_zatvaranja', sa.DateTime(), nullable=True),
    sa.Column('rok_rjesavanja', sa.Date(), nullable=True),
    sa.Column('korekcija', sa.Text(), nullable=True),
    sa.Column('analiza_uzroka', sa.Text(), nullable=True),
    sa.Column('uzrok_kategorija', sa.String(length=100), nullable=True),
    sa.Column('napomena', sa.Text(), nullable=True),
    sa.Column('vezana_nesukladnost', sa.String(length=50), nullable=True),
    sa.Column('promjene_sustava', sa.String(length=2), nullable=True),
    sa.Column('broj_promjene', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reklamacija_broj_predmeta'), 'reklamacija', ['broj_predmeta'], unique=True)
    op.create_index(op.f('ix_reklamacija_prioritet'), 'reklamacija', ['prioritet'], unique=False)
    op.create_index(op.f('ix_reklamacija_status'), 'reklamacija', ['status'], unique=False)
    op.create_index(op.f('ix_reklamacija_vrsta'), 'reklamacija', ['vrsta'], unique=False)
    op.create_table('capa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reklamacija_id', sa.Integer(), nullable=False),
    sa.Column('vrsta', sa.String(length=20), nullable=False),
    sa.Column('opis_mjere', sa.Text(), nullable=False),
    sa.Column('odgovorna_osoba', sa.String(length=100), nullable=False),
    sa.Column('rok_izvrsenja', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('datum_izvrsenja', sa.Date(), nullable=True),
    sa.Column('rezultat', sa.Text(), nullable=True),
    sa.Column('provjerio', sa.String(length=100), nullable=True),
    sa.Column('datum_provjere', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['reklamacija_id'], ['reklamacija.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capa_reklamacija_id'), 'capa', ['reklamacija_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_capa_reklamacija_id'), table_name='capa')
    op.drop_table('capa')
    op.drop_index(op.f('ix_reklamacija_vrsta'), table_name='reklamacija')
    op.drop_index(op.f('ix_reklamacija_status'), table_name='reklamacija')
    op.drop_index(op.f('ix_reklamacija_prioritet'), table_name='reklamacija')
    op.drop_index(op.f('ix_reklamacija_broj_predmeta'), table_name='reklamacija')
    op.drop_table('reklamacija')
    # ### end Alembic commands ###
