"""add pauk import fields to materijal

Revision ID: 4a6dd57b0dbf
Revises: 63ce88be07d0
Create Date: 2026-06-15 12:32:46.798274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a6dd57b0dbf'
down_revision: Union[str, Sequence[str], None] = '63ce88be07d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materijal', sa.Column('podgrupa2', sa.String(length=100), nullable=True))
    op.add_column('materijal', sa.Column('podgrupa3', sa.String(length=100), nullable=True))
    op.add_column('materijal', sa.Column('minimalno_pakiranje', sa.Numeric(precision=12, scale=3), nullable=True))
    op.add_column('materijal', sa.Column('dobavljac_naziv', sa.String(length=255), nullable=True))
    op.add_column('materijal', sa.Column('tarifni_broj', sa.String(length=50), nullable=True))
    op.add_column('materijal', sa.Column('zemlja_porijekla', sa.String(length=100), nullable=True))
    op.add_column('materijal', sa.Column('rok_trajanja', sa.String(length=50), nullable=True))
    op.add_column('materijal', sa.Column('rok_trajanja_godina', sa.Numeric(precision=5, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('materijal', 'rok_trajanja_godina')
    op.drop_column('materijal', 'rok_trajanja')
    op.drop_column('materijal', 'zemlja_porijekla')
    op.drop_column('materijal', 'tarifni_broj')
    op.drop_column('materijal', 'dobavljac_naziv')
    op.drop_column('materijal', 'minimalno_pakiranje')
    op.drop_column('materijal', 'podgrupa3')
    op.drop_column('materijal', 'podgrupa2')
    # ### end Alembic commands ###
