"""create materijali tables

Revision ID: 63ce88be07d0
Revises: 
Create Date: 2026-06-15 12:18:38.603359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63ce88be07d0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materijal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sifra', sa.String(length=50), nullable=False),
    sa.Column('sipo_sifra', sa.String(length=50), nullable=True),
    sa.Column('naziv', sa.String(length=255), nullable=False),
    sa.Column('jedinica', sa.String(length=20), nullable=False),
    sa.Column('kategorija', sa.String(length=100), nullable=True),
    sa.Column('tip', sa.String(length=100), nullable=True),
    sa.Column('grupa', sa.String(length=100), nullable=True),
    sa.Column('podgrupa', sa.String(length=100), nullable=True),
    sa.Column('aktivno', sa.Boolean(), nullable=False),
    sa.Column('minimalna_kolicina', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('dobavljac_id', sa.Integer(), nullable=True),
    sa.Column('napomena', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materijal_naziv'), 'materijal', ['naziv'], unique=False)
    op.create_index(op.f('ix_materijal_sifra'), 'materijal', ['sifra'], unique=True)
    op.create_table('cijena_povijest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('materijal_id', sa.Integer(), nullable=False),
    sa.Column('dobavljac_id', sa.Integer(), nullable=True),
    sa.Column('cijena', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('valuta', sa.String(length=3), nullable=False),
    sa.Column('datum_vazenja', sa.Date(), nullable=False),
    sa.Column('napomena', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['materijal_id'], ['materijal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cijena_povijest_materijal_id'), 'cijena_povijest', ['materijal_id'], unique=False)
    op.create_table('materijal_etiketa',
    sa.Column('materijal_id', sa.Integer(), nullable=False),
    sa.Column('kupac_id', sa.Integer(), nullable=True),
    sa.Column('papir_materijal_id', sa.Integer(), nullable=True),
    sa.Column('format_netto_x_mm', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('format_netto_y_mm', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('format_brutto_x_mm', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('format_brutto_y_mm', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('etiketa_u_kutiji', sa.Integer(), nullable=True),
    sa.Column('kutija_tip', sa.String(length=100), nullable=True),
    sa.Column('paleta_tip', sa.String(length=100), nullable=True),
    sa.Column('kutija_na_paleti', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['materijal_id'], ['materijal.id'], ),
    sa.ForeignKeyConstraint(['papir_materijal_id'], ['materijal.id'], ),
    sa.PrimaryKeyConstraint('materijal_id')
    )
    op.create_table('materijal_papir',
    sa.Column('materijal_id', sa.Integer(), nullable=False),
    sa.Column('tip_papira', sa.String(length=50), nullable=True),
    sa.Column('gramatura_g_m2', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('sirina_mm', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('duljina_role_m', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('format_arka_x_mm', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('format_arka_y_mm', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['materijal_id'], ['materijal.id'], ),
    sa.PrimaryKeyConstraint('materijal_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('materijal_papir')
    op.drop_table('materijal_etiketa')
    op.drop_index(op.f('ix_cijena_povijest_materijal_id'), table_name='cijena_povijest')
    op.drop_table('cijena_povijest')
    op.drop_index(op.f('ix_materijal_sifra'), table_name='materijal')
    op.drop_index(op.f('ix_materijal_naziv'), table_name='materijal')
    op.drop_table('materijal')
    # ### end Alembic commands ###
