"""add remaining pauk fields to materijal

Revision ID: 833170c83337
Revises: 4a6dd57b0dbf
Create Date: 2026-06-15 12:53:37.578704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '833170c83337'
down_revision: Union[str, Sequence[str], None] = '4a6dd57b0dbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materijal', sa.Column('podgrupa4', sa.String(length=100), nullable=True))
    op.add_column('materijal', sa.Column('rok_dobavljivosti', sa.Integer(), nullable=True))
    op.add_column('materijal', sa.Column('lokacija_skladiste', sa.String(length=100), nullable=True))
    op.add_column('materijal', sa.Column('pozicija', sa.String(length=100), nullable=True))
    op.add_column('materijal', sa.Column('ulazno_skladiste_1', sa.String(length=100), nullable=True))
    op.add_column('materijal', sa.Column('ulazno_skladiste_2', sa.String(length=100), nullable=True))
    op.add_column('materijal', sa.Column('prijelazno_skladiste_1', sa.String(length=100), nullable=True))
    op.add_column('materijal', sa.Column('prijelazno_skladiste_2', sa.String(length=100), nullable=True))
    op.add_column('materijal', sa.Column('prijelazno_skladiste_3', sa.String(length=100), nullable=True))
    op.add_column('materijal', sa.Column('mjesto_troska_1', sa.String(length=50), nullable=True))
    op.add_column('materijal', sa.Column('mjesto_troska_2', sa.String(length=50), nullable=True))
    op.add_column('materijal', sa.Column('mjesto_troska_3', sa.String(length=50), nullable=True))
    op.add_column('materijal', sa.Column('mjesto_troska_4', sa.String(length=50), nullable=True))
    op.add_column('materijal', sa.Column('mjesto_troska_5', sa.String(length=50), nullable=True))
    op.add_column('materijal', sa.Column('mjesto_troska_6', sa.String(length=50), nullable=True))
    op.add_column('materijal', sa.Column('mjesto_troska_7', sa.String(length=50), nullable=True))
    op.add_column('materijal', sa.Column('mjesto_troska_8', sa.String(length=50), nullable=True))
    op.add_column('materijal', sa.Column('mjesto_troska_9', sa.String(length=50), nullable=True))
    op.add_column('materijal', sa.Column('datoteke', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('materijal', 'datoteke')
    op.drop_column('materijal', 'mjesto_troska_9')
    op.drop_column('materijal', 'mjesto_troska_8')
    op.drop_column('materijal', 'mjesto_troska_7')
    op.drop_column('materijal', 'mjesto_troska_6')
    op.drop_column('materijal', 'mjesto_troska_5')
    op.drop_column('materijal', 'mjesto_troska_4')
    op.drop_column('materijal', 'mjesto_troska_3')
    op.drop_column('materijal', 'mjesto_troska_2')
    op.drop_column('materijal', 'mjesto_troska_1')
    op.drop_column('materijal', 'prijelazno_skladiste_3')
    op.drop_column('materijal', 'prijelazno_skladiste_2')
    op.drop_column('materijal', 'prijelazno_skladiste_1')
    op.drop_column('materijal', 'ulazno_skladiste_2')
    op.drop_column('materijal', 'ulazno_skladiste_1')
    op.drop_column('materijal', 'pozicija')
    op.drop_column('materijal', 'lokacija_skladiste')
    op.drop_column('materijal', 'rok_dobavljivosti')
    op.drop_column('materijal', 'podgrupa4')
    # ### end Alembic commands ###
