"""add extended pauk fields and pantone table

Revision ID: 90c84fcbe81a
Revises: 833170c83337
Create Date: 2026-06-15 13:20:05.736175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90c84fcbe81a'
down_revision: Union[str, Sequence[str], None] = '833170c83337'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pantone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kod', sa.String(length=30), nullable=False),
    sa.Column('naziv', sa.String(length=100), nullable=True),
    sa.Column('hex_boja', sa.String(length=7), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pantone_kod'), 'pantone', ['kod'], unique=True)
    op.add_column('materijal', sa.Column('promjer_mm', sa.Numeric(precision=10, scale=3), nullable=True))
    op.add_column('materijal', sa.Column('debljina_um', sa.Numeric(precision=10, scale=3), nullable=True))
    op.add_column('materijal', sa.Column('duljina_mm', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('materijal', sa.Column('sirina_mm', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('materijal', sa.Column('visina_mm', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('materijal', sa.Column('povrsina_mm2', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('materijal', sa.Column('volumen_mm3', sa.Numeric(precision=16, scale=2), nullable=True))
    op.add_column('materijal', sa.Column('gramatura_g_m2', sa.Numeric(precision=8, scale=2), nullable=True))
    op.add_column('materijal', sa.Column('kvaliteta', sa.String(length=100), nullable=True))
    op.add_column('materijal', sa.Column('kutija_na_paleti_z', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('materijal', sa.Column('tezina_kg', sa.Numeric(precision=10, scale=3), nullable=True))
    op.add_column('materijal', sa.Column('hilzna', sa.String(length=50), nullable=True))
    op.add_column('materijal', sa.Column('litraza', sa.Numeric(precision=10, scale=3), nullable=True))
    op.add_column('materijal', sa.Column('tehnicki_naziv', sa.String(length=255), nullable=True))
    op.add_column('materijal', sa.Column('raspored', sa.String(length=255), nullable=True))
    op.add_column('materijal', sa.Column('opis_en', sa.Text(), nullable=True))
    op.add_column('materijal', sa.Column('posebna_napomena', sa.Text(), nullable=True))
    op.add_column('materijal', sa.Column('napomena_dorada', sa.Text(), nullable=True))
    op.add_column('materijal', sa.Column('oznaka', sa.String(length=100), nullable=True))
    op.add_column('materijal', sa.Column('tehnika', sa.String(length=100), nullable=True))
    op.add_column('materijal', sa.Column('tip_dorade', sa.String(length=100), nullable=True))
    op.add_column('materijal', sa.Column('komplet', sa.String(length=100), nullable=True))
    op.add_column('materijal', sa.Column('nacrt', sa.String(length=100), nullable=True))
    op.add_column('materijal', sa.Column('sistem', sa.String(length=100), nullable=True))
    op.add_column('materijal', sa.Column('namotaj', sa.String(length=100), nullable=True))
    op.add_column('materijal', sa.Column('podloga', sa.String(length=100), nullable=True))
    op.add_column('materijal', sa.Column('bazni_papir', sa.String(length=100), nullable=True))
    op.add_column('materijal', sa.Column('materijal_tisak', sa.String(length=100), nullable=True))
    op.add_column('materijal', sa.Column('boja', sa.String(length=100), nullable=True))
    op.add_column('materijal', sa.Column('pantone_id', sa.Integer(), nullable=True))
    op.add_column('materijal', sa.Column('coated', sa.Boolean(), nullable=True))
    op.add_column('materijal', sa.Column('folija', sa.Boolean(), nullable=True))
    op.add_column('materijal', sa.Column('lugootporno', sa.String(length=50), nullable=True))
    op.add_column('materijal', sa.Column('prehrana', sa.String(length=50), nullable=True))
    op.add_column('materijal', sa.Column('jednokomp_dvokomp', sa.String(length=50), nullable=True))
    op.add_column('materijal', sa.Column('svjetlostabilnost', sa.String(length=50), nullable=True))
    op.add_column('materijal', sa.Column('certifikati', sa.String(length=255), nullable=True))
    op.add_column('materijal', sa.Column('inventarni_broj', sa.String(length=100), nullable=True))
    op.add_column('materijal', sa.Column('ura', sa.String(length=50), nullable=True))
    op.add_column('materijal', sa.Column('proizvodni_broj', sa.String(length=100), nullable=True))
    op.add_column('materijal', sa.Column('kljucni_broj_otpada', sa.String(length=50), nullable=True))
    op.add_column('materijal', sa.Column('qr_nije_potreban', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('materijal', sa.Column('zabranjeno_medjuskladiste', sa.Boolean(), nullable=False, server_default=sa.false()))
    with op.batch_alter_table('materijal') as batch_op:
        batch_op.create_foreign_key('fk_materijal_pantone_id_pantone', 'pantone', ['pantone_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materijal') as batch_op:
        batch_op.drop_constraint('fk_materijal_pantone_id_pantone', type_='foreignkey')
    op.drop_column('materijal', 'zabranjeno_medjuskladiste')
    op.drop_column('materijal', 'qr_nije_potreban')
    op.drop_column('materijal', 'kljucni_broj_otpada')
    op.drop_column('materijal', 'proizvodni_broj')
    op.drop_column('materijal', 'ura')
    op.drop_column('materijal', 'inventarni_broj')
    op.drop_column('materijal', 'certifikati')
    op.drop_column('materijal', 'svjetlostabilnost')
    op.drop_column('materijal', 'jednokomp_dvokomp')
    op.drop_column('materijal', 'prehrana')
    op.drop_column('materijal', 'lugootporno')
    op.drop_column('materijal', 'folija')
    op.drop_column('materijal', 'coated')
    op.drop_column('materijal', 'pantone_id')
    op.drop_column('materijal', 'boja')
    op.drop_column('materijal', 'materijal_tisak')
    op.drop_column('materijal', 'bazni_papir')
    op.drop_column('materijal', 'podloga')
    op.drop_column('materijal', 'namotaj')
    op.drop_column('materijal', 'sistem')
    op.drop_column('materijal', 'nacrt')
    op.drop_column('materijal', 'komplet')
    op.drop_column('materijal', 'tip_dorade')
    op.drop_column('materijal', 'tehnika')
    op.drop_column('materijal', 'oznaka')
    op.drop_column('materijal', 'napomena_dorada')
    op.drop_column('materijal', 'posebna_napomena')
    op.drop_column('materijal', 'opis_en')
    op.drop_column('materijal', 'raspored')
    op.drop_column('materijal', 'tehnicki_naziv')
    op.drop_column('materijal', 'litraza')
    op.drop_column('materijal', 'hilzna')
    op.drop_column('materijal', 'tezina_kg')
    op.drop_column('materijal', 'kutija_na_paleti_z')
    op.drop_column('materijal', 'kvaliteta')
    op.drop_column('materijal', 'gramatura_g_m2')
    op.drop_column('materijal', 'volumen_mm3')
    op.drop_column('materijal', 'povrsina_mm2')
    op.drop_column('materijal', 'visina_mm')
    op.drop_column('materijal', 'sirina_mm')
    op.drop_column('materijal', 'duljina_mm')
    op.drop_column('materijal', 'debljina_um')
    op.drop_column('materijal', 'promjer_mm')
    op.drop_index(op.f('ix_pantone_kod'), table_name='pantone')
    op.drop_table('pantone')
    # ### end Alembic commands ###
