"""skladiste_foundation

Revision ID: da93a22079c1
Revises: 177e4f5997ff
Create Date: 2026-06-24 09:01:14.301816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da93a22079c1'
down_revision: Union[str, Sequence[str], None] = '177e4f5997ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datum_pocetka', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('datum_kraja', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paleta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qr_raw', sa.String(length=255), nullable=False),
    sa.Column('sifra', sa.String(length=60), nullable=True),
    sa.Column('naziv', sa.String(length=255), nullable=True),
    sa.Column('lot', sa.String(length=80), nullable=True),
    sa.Column('kolicina', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('jedinica', sa.String(length=20), nullable=True),
    sa.Column('datum_ulaza', sa.Date(), nullable=True),
    sa.Column('rok_trajanja', sa.Date(), nullable=True),
    sa.Column('pozicija', sa.String(length=20), nullable=False),
    sa.Column('datum_in', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('datum_out', sa.DateTime(), nullable=True),
    sa.Column('izvor', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paleta_datum_out'), 'paleta', ['datum_out'], unique=False)
    op.create_index(op.f('ix_paleta_pozicija'), 'paleta', ['pozicija'], unique=False)
    op.create_index(op.f('ix_paleta_qr_raw'), 'paleta', ['qr_raw'], unique=False)
    op.create_index(op.f('ix_paleta_rok_trajanja'), 'paleta', ['rok_trajanja'], unique=False)
    op.create_index(op.f('ix_paleta_sifra'), 'paleta', ['sifra'], unique=False)
    op.create_index('uq_paleta_aktivna_pozicija', 'paleta', ['pozicija'], unique=True, sqlite_where=sa.text('datum_out IS NULL'), postgresql_where=sa.text('datum_out IS NULL'))
    op.create_table('prijem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sifra', sa.String(length=60), nullable=True),
    sa.Column('broj_paleta', sa.Integer(), nullable=False),
    sa.Column('datum_plan', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prioritet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sifra', sa.String(length=60), nullable=False),
    sa.Column('mod', sa.String(length=20), nullable=False),
    sa.Column('rack_ids', sa.Text(), nullable=True),
    sa.Column('napomena', sa.Text(), nullable=True),
    sa.Column('aktivan', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prioritet_sifra'), 'prioritet', ['sifra'], unique=False)
    op.create_table('skladiste_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tip', sa.String(length=40), nullable=False),
    sa.Column('poruka', sa.Text(), nullable=True),
    sa.Column('detalji', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skladiste_event_timestamp'), 'skladiste_event', ['timestamp'], unique=False)
    op.create_table('inventura_stavka',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inventura_id', sa.Integer(), nullable=False),
    sa.Column('qr_raw', sa.String(length=255), nullable=False),
    sa.Column('pozicija_skenirana', sa.String(length=20), nullable=True),
    sa.Column('datum_skeniranja', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['inventura_id'], ['inventura.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventura_stavka_inventura_id'), 'inventura_stavka', ['inventura_id'], unique=False)
    op.create_table('prijem_stavka',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prijem_id', sa.Integer(), nullable=False),
    sa.Column('redni_broj', sa.Integer(), nullable=False),
    sa.Column('pozicija', sa.String(length=20), nullable=False),
    sa.Column('qr_raw', sa.String(length=255), nullable=True),
    sa.Column('datum_potvrda', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['prijem_id'], ['prijem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prijem_stavka_prijem_id'), 'prijem_stavka', ['prijem_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prijem_stavka_prijem_id'), table_name='prijem_stavka')
    op.drop_table('prijem_stavka')
    op.drop_index(op.f('ix_inventura_stavka_inventura_id'), table_name='inventura_stavka')
    op.drop_table('inventura_stavka')
    op.drop_index(op.f('ix_skladiste_event_timestamp'), table_name='skladiste_event')
    op.drop_table('skladiste_event')
    op.drop_index(op.f('ix_prioritet_sifra'), table_name='prioritet')
    op.drop_table('prioritet')
    op.drop_table('prijem')
    op.drop_index('uq_paleta_aktivna_pozicija', table_name='paleta', sqlite_where=sa.text('datum_out IS NULL'), postgresql_where=sa.text('datum_out IS NULL'))
    op.drop_index(op.f('ix_paleta_sifra'), table_name='paleta')
    op.drop_index(op.f('ix_paleta_rok_trajanja'), table_name='paleta')
    op.drop_index(op.f('ix_paleta_qr_raw'), table_name='paleta')
    op.drop_index(op.f('ix_paleta_pozicija'), table_name='paleta')
    op.drop_index(op.f('ix_paleta_datum_out'), table_name='paleta')
    op.drop_table('paleta')
    op.drop_table('inventura')
    # ### end Alembic commands ###
